config/routes.rb
Rails.application.routes.draw do
  resources :clients do
  	collection do
  		get 'running'
  	end
  end
  resources :advocates
  resources :case_files do
  	collection do
  		get 'completed'
  		get 'upcoming'
  	end
  end
  get '/', to: 'dashboard#index', as: 'dashboard'
  get '/search', to: 'dashboard#search', as: 'search'
end

app/models/case_file.rb
class CaseFile < ApplicationRecord
	belongs_to :advocate
	belongs_to :client
	enum status: [:Running, :Closed]

	scope :active, -> {where(status: :Running)}
	scope :completed, -> { where("convocation_on < ?", Date.today) }
	scope :upcoming, -> { where("convocation_on > ?", Date.today) }
	

	def self.search(search)
	  where("name LIKE ?", "%#{search}%") or
	  where("file_received_on LIKE ?", "%#{search}%") or
	  where("appeal_on LIKE ?", "%#{search}%") or
	  where("convocation_on LIKE ?", "%#{search}%") or
	  where("amount_paid LIKE ?", "%#{search}%") or
	  where("status LIKE ?", "%#{search}%")
	end
end

app/controllers/case_files_controller.rb
class CaseFilesController < ApplicationController
  before_action :set_case_file, only: [:show, :edit, :update, :destroy]

  # GET /case_files
  # GET /case_files.json
  def index
    @case_files = CaseFile.all
  end

  # GET /case_files/completed
  # GET /case_files/completed.json
  def completed
    @heading = 'Completed'
    @case_files = CaseFile.completed
    render :index
  end

  # GET /case_files/upcoming
  # GET /case_files/upcoming.json
  def upcoming
    @heading = 'Upcoming'
    @case_files = CaseFile.upcoming
    render :index
  end

  # GET /case_files/1
  # GET /case_files/1.json
  def show
  end

  # GET /case_files/new
  def new
    @case_file = CaseFile.new
    @advocates = Advocate.all()
    @clients = Client.all()
  end

  # GET /case_files/1/edit
  def edit
    @advocates = Advocate.all()
    @clients = Client.all()
  end

  # POST /case_files
  # POST /case_files.json
  def create
    @case_file = CaseFile.new(case_file_params)

    respond_to do |format|
      if @case_file.save
        format.html { redirect_to @case_file, notice: 'Case file was successfully created.' }
        format.json { render :show, status: :created, location: @case_file }
      else
        format.html { render :new }
        format.json { render json: @case_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /case_files/1
  # PATCH/PUT /case_files/1.json
  def update
    respond_to do |format|
      if @case_file.update(case_file_params)
        format.html { redirect_to @case_file, notice: 'Case file was successfully updated.' }
        format.json { render :show, status: :ok, location: @case_file }
      else
        format.html { render :edit }
        format.json { render json: @case_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /case_files/1
  # DELETE /case_files/1.json
  def destroy
    @case_file.destroy
    respond_to do |format|
      format.html { redirect_to case_files_url, notice: 'Case file was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_case_file
      @case_file = CaseFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def case_file_params
      params.require(:case_file).permit(:name, :file_received_on, :advocate_id, :client_id, :appeal_on, :convocation_on, :amount_paid, :status)
    end
end

app/helpers/case_files_helper.rb
module CaseFilesHelper
end

app/views/case_files/_form.html.erb
<%= form_for(case_file, html: {role: 'form', class: 'form-horizontal'}) do |f| %>
<% if case_file.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(case_file.errors.count, "error") %> prohibited this case_file from being saved:</h2>

  <ul>
    <% case_file.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <div class="col-lg-10 col-lg-offset-1">
    <%= f.label :name, class: 'sr-only' %>
    <%= f.text_field :name, class: 'form-control', placeholder: 'Case Name' %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-3 col-lg-offset-1" align="left">
    <%= f.label "case_file[advocate_id]", "Adovcate Name" %>
  </div>
  <div class="col-lg-7">
    <%= select_tag "case_file[advocate_id]", options_from_collection_for_select(@advocates, "id", "name", @case_file.advocate_id), class: 'form-control' %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-3 col-lg-offset-1" align="left">
    <%= f.label 'case_file[client_id]', "Client Name" %>
  </div>
  <div class="col-lg-7">
    <%= select_tag 'case_file[client_id]', options_from_collection_for_select(@clients, "id", "name", @case_file.client_id), class: 'form-control' %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-3 col-lg-offset-1" align="left">
    <%= f.label :file_received_on, "Received On" %>
  </div>
  <div class="col-lg-7">
    <%= f.date_select :file_received_on, {}, {class: 'form-control form-control-date'} %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-3 col-lg-offset-1" align="left">
    <%= f.label :appeal_on, "Appeal On" %>
  </div>
  <div class="col-lg-7">
    <%= f.date_select :appeal_on, {}, {class: 'form-control form-control-date'} %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-3 col-lg-offset-1" align="left">
    <%= f.label :convocation_on, "Convocation On" %>
  </div>
  <div class="col-lg-7">
    <%= f.date_select :convocation_on, {}, {class: 'form-control form-control-date'} %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-10 col-lg-offset-1">
    <%= f.label :amount_paid, class: 'sr-only' %>
    <%= f.text_field :amount_paid, class: 'form-control', placeholder: 'Amount Paid' %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-10 col-lg-offset-1">
    <%= f.label :status, class: 'sr-only' %>
    <%= f.select :status, CaseFile.statuses.keys, {}, {class: 'form-control'} %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-10 col-lg-offset-1">
  <%= f.submit "Submit", class: 'btn btn-success btn-block' %>
  </div>
</div>
<% end %>

app/views/case_files/edit.html.erb
<div class="page-header">
	<div class="row">
		<div class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
		<div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
			<div class="row">
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
				  <h2>Editing <small>Case File</small> <%= @case_file.name %></h2>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
					<!-- <h2><strong>Status</strong></h2> -->
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
				</div>
			</div>
		</div>
		<div class="col-lg-1 col-md-1 col-sm-1 col-xs-1"></div>
	</div>
</div>

<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
		<%= render 'form', case_file: @case_file %>

		<%= link_to 'Show', @case_file %> |
		<%= link_to 'Back', case_files_path %>
	</div>
</div>

app/views/case_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @heading if !@heading.nil? %> Case Files</h1>

<div class="table-responsive">
  <table class="table table-hover">
    <tr>
      <th>Name</th>
      <th>File received on</th>
      <th>Advocate</th>
      <th>Client</th>
      <th>Appeal on</th>
      <th>Convocation on</th>
      <th>Amount paid</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @case_files.each do |case_file| %>
      <tr>
        <td><%= case_file.name %></td>
        <td><%= case_file.file_received_on %></td>
        <td><%= case_file.advocate_id %></td>
        <td><%= case_file.client_id %></td>
        <td><%= case_file.appeal_on %></td>
        <td><%= case_file.convocation_on %></td>
        <td><%= case_file.amount_paid %></td>
        <td><%= case_file.status %></td>
        <td><%= link_to 'Show', case_file %></td>
        <td><%= link_to 'Edit', edit_case_file_path(case_file) %></td>
        <td><%= link_to 'Destroy', case_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Case File', new_case_file_path %>

app/views/case_files/new.html.erb
<div class="row" align="center">
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
	</div>
	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
		<div class="row">
			<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
				<a class="btn btn-nav" href="<%= case_files_path %>"> <i class="fa fa-list-ol fa-2x"></i></a>
			</div>
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
				<h2>New<small> Case File</small></h2>
			</div>
		</div>
	</div>
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
</div>
<div class="row" align="center">
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
	</div>
	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
		<%= render 'form', case_file: @case_file %>
	</div>
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
</div>

app/views/case_files/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File received on:</strong>
  <%= @case_file.file_received_on %>
</p>

<p>
  <strong>Advocate:</strong>
  <%= @case_file.advocate.name %>
</p>

<p>
  <strong>Client:</strong>
  <%= @case_file.client.name %>
</p>

<p>
  <strong>Appeal on:</strong>
  <%= @case_file.appeal_on %>
</p>

<p>
  <strong>Convocation on:</strong>
  <%= @case_file.convocation_on %>
</p>

<p>
  <strong>Amount paid:</strong>
  <%= @case_file.amount_paid %>
</p>

<p>
  <strong>Status:</strong>
  <%= @case_file.status %>
</p>

<%= link_to 'Edit', edit_case_file_path(@case_file) %> |
<%= link_to 'Back', case_files_path %>