config/routes.rb
Rails.application.routes.draw do
  resources :clients do
  	collection do
  		get 'running'
  	end
  end
  resources :advocates
  resources :case_files do
  	collection do
  		get 'completed'
  		get 'upcoming'
  	end
  end
  get '/', to: 'dashboard#index', as: 'dashboard'
  get '/search', to: 'dashboard#search', as: 'search'
end

app/models/client.rb
class Client < ApplicationRecord
	has_many :case_files
	def name
		return self.f_name + ' ' + self.l_name
	end

	scope :running, -> { joins(:case_files).merge(CaseFile.active) }

	def self.search(search)
	  where("f_name LIKE ?", "%#{search}%") or
	  where("l_name LIKE ?", "%#{search}%") or
	  where("dob LIKE ?", "%#{search}%") or
	  where("phone LIKE ?", "%#{search}%")
	end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients/running
  # GET /clients/running.json
  def running
    @heading = 'Running'
    @clients = Client.running
    render :index
  end

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:f_name, :l_name, :dob, :phone)
    end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for(client, html: {role: 'form', class: 'form-horizontal'}) do |f| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
  <div class="col-lg-10 col-lg-offset-1">
  <%= f.label :f_name, class: 'sr-only' %>
    <%= f.text_field :f_name, class: 'form-control', placeholder: 'First Name' %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-10 col-lg-offset-1">
  <%= f.label :l_name, class: 'sr-only' %>
  <%= f.text_field :l_name, class: 'form-control', placeholder: 'Last Name' %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-2 col-lg-offset-1" align="left">
    <%= f.label :dob, "Date of Birth" %>
  </div>
  <div class="col-lg-8">
    <%= f.date_select :dob, {}, {class: 'form-control form-control-date'} %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-10 col-lg-offset-1">
  <%= f.label :phone, class: 'sr-only' %>
  <%= f.text_field :phone, class: 'form-control', placeholder: 'Phone' %>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-10 col-lg-offset-1">
  <%= f.submit 'Submit', class: 'btn btn-success btn-block' %>
  </div>
</div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @heading if !@heading.nil? %> Clients</h1>

<div class="table-responsive">
  <table class="table table-hover">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Date of Birth</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr>
        <td><%= client.f_name %></td>
        <td><%= client.l_name %></td>
        <td><%= client.dob %></td>
        <td><%= client.phone %></td>
        <td><%= link_to 'Show', client %></td>
        <td><%= link_to 'Edit', edit_client_path(client) %></td>
        <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<div class="row" align="center">
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
	</div>
	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
		<div class="row">
			<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
				<a class="btn btn-nav" href="<%= clients_path %>"> <i class="fa fa-list-ol fa-2x"></i></a>
			</div>
			<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
				<h2>New<small> Client</small></h2>
			</div>
		</div>
	</div>
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
</div>
<div class="row" align="center">
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2">
	</div>
	<div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
		<%= render 'form', client: @client %>
	</div>
	<div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"></div>
</div>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>F name:</strong>
  <%= @client.f_name %>
</p>

<p>
  <strong>L name:</strong>
  <%= @client.l_name %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @client.dob %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>